# `sheldon` configuration file
# ----------------------------
#
# You can modify this file directly or you can use one of the following
# `sheldon` commands which are provided to assist in editing the config file:
#
# - `sheldon add` to add a new plugin to the config file
# - `sheldon edit` to open up the config file in the default editor
# - `sheldon remove` to remove a plugin from the config file
#
# See the documentation for more https://github.com/rossmacarthur/sheldon#readme

shell = 'zsh'

[plugins.zsh-defer]
github = 'romkatv/zsh-defer'

[templates]		# sheldon 0.7.4
defer = "{{ hooks?.pre | nl }}{% for file in files %}zsh-defer source \"{{ file }}\"\n{% endfor %}{{ hooks?.post | nl }}"

[plugins.environment]
github = 'zimfw/environment'
apply = ["defer"]

[plugins.compinit]
inline = 'autoload -Uz compinit && zsh-defer compinit'

[plugins.colors]
inline = 'autoload -Uz colors && zsh-defer colors'

[plugins.zsh-input]
github = "zimfw/input"
apply = ["defer"]

[plugins.mise]
inline = 'eval "$(mise activate zsh)"'

[plugins.starship]
inline = 'eval "$(starship init zsh)"'

[plugins.zsh-fzf]
github = 'zimfw/fzf'
apply = ["defer"]
hooks.pre =	 """zsh-defer source /usr/share/doc/fzf/examples/key-bindings.zsh
				zsh-defer source /usr/share/doc/fzf/examples/completion.zsh"""

[plugins.zsh-autosuggestions]
github = 'zsh-users/zsh-autosuggestions'
apply = ["defer"]
hooks.post = "ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=#888'"


[plugins.zsh-completions]
github = "zsh-users/zsh-completions"
apply = ["defer"]
hooks.post = """zstyle ':completion:*:(processes|jobs)' menu yes select=2
				zstyle ':completion:*' matcher-list 'm:{[:lower:]}={[:upper:]}' '+m:{[:upper:]}={[:lower:]}'"""		# わざわざ大文字を入力した時は小文字の候補を補完しない。でもやっぱり大文字の候補が見つからない場合には, 小文字の候補を補完する


#[plugins.zsh-autocomplete]
#github = 'marlonrichert/zsh-autocomplete'
#apply = ["defer"]
#hooks.post """zstyle '*:compinit' arguments -D -i -u -C -w
#			zstyle ':autocomplete:*' insert-unambiguous yes
#			zstyle ':autocomplete:*' fzf-completion yes"""

[plugins.zsh-dwim]
github = "oknowton/zsh-dwim"
apply = ["defer"]

[plugins.zsh-z]
github = "rupa/z"
apply = ["defer"]


[plugins.zsh-syntax-highlighting]
github = "zsh-users/zsh-syntax-highlighting"
hooks.post = """ZSH_HIGHLIGHT_HIGHLIGHTERS=(main brackets)
				typeset -A ZSH_HIGHLIGHT_STYLES
				ZSH_HIGHLIGHT_STYLES[path]='fg=yellow'"""


#[plugins.zsh-history-substring-search]
#github = 'zsh-users/zsh-history-substring-search'
#apply = ["defer"]
#hooks.post = """bindkey '^K' history-substring-search-up
#			bindkey '^J' history-substring-search-down
#			HISTORY_SUBSTRING_SEARCH_ENSURE_UNIQUE=1"""


[plugins.wezterm]
local = '~/dotfiles/d/zsh'
use = ['wezterm.sh']
apply = ['defer']

[plugins.dotfiles-defer]
local = '~/dotfiles/d/zsh/sheldon'
use = ['defer.zsh']
apply = ['defer']

[plugins.dotfiles-sync]
local = '~/dotfiles/d/zsh/sheldon'
use = ['sync.zsh']
apply = ['source']

# ----
# [plugins]

# For example:
#
# [plugins.base16]
# github = "chriskempson/base16-shell"


